<a href="https://colab.research.google.com/github/nehansa2003/Weather-Forecasting-Project/blob/main/Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

In [2]:
drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
dataset='/content/drive/MyDrive/Capstone_Datasets/weather_data_processed_2020_2025.parquet'

In [4]:
# Load Parquet dataset
weather_df = pd.read_parquet(
    dataset,
    engine="pyarrow"
)

print("Dataset loaded successfully!")

print("\nShape:")
print(weather_df.shape)

print("\nColumns:")
print(weather_df.columns.tolist())

print("\nDate range:")
print(weather_df["datetime"].min())
print("to")
print(weather_df["datetime"].max())

print("\nDistricts:")
print(weather_df["district"].unique())

print("\nGeographical points:")
print(weather_df["global_pointid"].nunique())

display(weather_df.head())

Dataset loaded successfully!

Shape:
(5629056, 26)

Columns:
['district', 'pointid', 'global_pointid', 'latitude', 'longitude', 'elevation_m', 'datetime', 'date', 'day', 'month', 'year', 'time', 'season', 'temperature_c', 'feelslike_c', 'humidity_pct', 'dewpoint_c', 'pressure_hpa', 'windspeed_kmh', 'winddirection_deg', 'winddirection_compass', 'windgust_kmh', 'rainfall_mm', 'cloudcover_pct', 'solarradiation_wm2', 'sunshineduration_s']

Date range:
2020-01-01 00:00:00
to
2025-12-31 23:00:00

Districts:
['Colombo' 'Galle' 'Gampaha' 'Jaffna' 'Kandy']

Geographical points:
107

,district,pointid,global_pointid,latitude,longitude,elevation_m,datetime,date,day,month,...,dewpoint_c,pressure_hpa,windspeed_kmh,winddirection_deg,winddirection_compass,windgust_kmh,rainfall_mm,cloudcover_pct,solarradiation_wm2,sunshineduration_s
0,Colombo,1,COL_001,6.85991,79.79351,0.0,2020-01-01 00:00:00,2020-01-01,1,1,...,24.0,1012.2,9.0,157,SSE,22.0,0.1,43,0.0,0.0
1,Colombo,1,COL_001,6.85991,79.79351,0.0,2020-01-01 01:00:00,2020-01-01,1,1,...,23.9,1011.7,5.5,148,SSE,15.8,0.0,50,0.0,0.0
2,Colombo,1,COL_001,6.85991,79.79351,0.0,2020-01-01 02:00:00,2020-01-01,1,1,...,24.0,1011.1,4.3,156,SSE,9.7,0.1,78,0.0,0.0
3,Colombo,1,COL_001,6.85991,79.79351,0.0,2020-01-01 03:00:00,2020-01-01,1,1,...,23.9,1010.4,3.9,146,SE,8.6,0.1,92,0.0,0.0
4,Colombo,1,COL_001,6.85991,79.79351,0.0,2020-01-01 04:00:00,2020-01-01,1,1,...,23.8,1010.5,3.6,96,E,7.2,0.0,90,0.0,0.0

Variable Information

In [6]:
variable_info = pd.DataFrame({
    "Column": weather_df.columns,
    "Data_Type": weather_df.dtypes.astype(str),
    "Non_Null_Count": weather_df.notna().sum().values,
    "Missing_Count": weather_df.isna().sum().values,
    "Missing_Percentage": (
        weather_df.isna().mean().values * 100
    ),
    "Unique_Values": weather_df.nunique().values
})

display(variable_info)

,Column,Data_Type,Non_Null_Count,Missing_Count,Missing_Percentage,Unique_Values
district,district,object,5629056,0,0.0,5
pointid,pointid,int64,5629056,0,0.0,33
global_pointid,global_pointid,object,5629056,0,0.0,107
latitude,latitude,float64,5629056,0,0.0,27
longitude,longitude,float64,5629056,0,0.0,29
elevation_m,elevation_m,float64,5629056,0,0.0,66
datetime,datetime,datetime64[ns],5629056,0,0.0,52608
date,date,object,5629056,0,0.0,2192
day,day,int64,5629056,0,0.0,31
month,month,int64,5629056,0,0.0,12
year,year,int64,5629056,0,0.0,6
time,time,object,5629056,0,0.0,24
season,season,object,5629056,0,0.0,4
temperature_c,temperature_c,float64,5629056,0,0.0,294
feelslike_c,feelslike_c,float64,5629056,0,0.0,368
humidity_pct,humidity_pct,int64,5629056,0,0.0,88
dewpoint_c,dewpoint_c,float64,5629056,0,0.0,304
pressure_hpa,pressure_hpa,float64,5629056,0,0.0,235
windspeed_kmh,windspeed_kmh,float64,5629056,0,0.0,598
winddirection_deg,winddirection_deg,int64,5629056,0,0.0,361
winddirection_compass,winddirection_compass,object,5629056,0,0.0,16
windgust_kmh,windgust_kmh,float64,5629056,0,0.0,329
rainfall_mm,rainfall_mm,float64,5629056,0,0.0,364
cloudcover_pct,cloudcover_pct,int64,5629056,0,0.0,101
solarradiation_wm2,solarradiation_wm2,float64,5629056,0,0.0,1098
sunshineduration_s,sunshineduration_s,float64,5629056,0,0.0,199680