<a href="https://colab.research.google.com/github/nehansa2003/Weather-Forecasting-Project/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import os
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Load Datasets

In [6]:
colombo=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Colombo.csv')
galle=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Galle.csv')
gampaha=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Gampaha.csv')
kandy=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Kandy.csv')
jaffna=pd.read_csv('/content/drive/MyDrive/Capstone_Datasets/Jaffna.csv')

In [7]:
print("Colombo :", colombo.shape)
print("Gampaha :", gampaha.shape)
print("Galle   :", galle.shape)
print("Kandy   :", kandy.shape)
print("Jaffna  :", jaffna.shape)

Colombo : (578688, 27)
Gampaha : (894336, 27)
Galle   : (1525632, 27)
Kandy   : (1736064, 27)
Jaffna  : (894336, 27)

Basic Dataset Inspection

In [8]:
datasets = {
    "Colombo": colombo,
    "Gampaha": gampaha,
    "Galle": galle,
    "Kandy": kandy,
    "Jaffna": jaffna
}

for district, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"{district.upper()} DATASET")
    print("=" * 70)

    print("Shape:", df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData types:")
    print(df.dtypes)

    print("\nFirst 5 rows:")
    display(df.head())

======================================================================
COLOMBO DATASET
======================================================================
Shape: (578688, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Colombo,1,6.85991,79.79351,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,9.0,157,SSE,22.0,0.1,0.1,43,0.0,0.0,NaN
1,Colombo,1,6.85991,79.79351,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,5.5,148,SSE,15.8,0.0,0.0,50,0.0,0.0,NaN
2,Colombo,1,6.85991,79.79351,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,4.3,156,SSE,9.7,0.1,0.1,78,0.0,0.0,NaN
3,Colombo,1,6.85991,79.79351,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,3.9,146,SE,8.6,0.1,0.1,92,0.0,0.0,NaN
4,Colombo,1,6.85991,79.79351,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,3.6,96,E,7.2,0.0,0.0,90,0.0,0.0,NaN

======================================================================
GAMPAHA DATASET
======================================================================
Shape: (894336, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,8.1,148,SSE,20.9,0.1,0.1,34,0.0,0.0,NaN
1,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,6.4,133,SE,14.4,0.0,0.0,50,0.0,0.0,NaN
2,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,4.8,138,SE,11.9,0.0,0.0,81,0.0,0.0,NaN
3,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,3.7,119,ESE,9.0,0.0,0.0,92,0.0,0.0,NaN
4,Gampaha,1,6.97796,79.88538,4.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,4.4,81,E,8.6,0.0,0.0,91,0.0,0.0,NaN

======================================================================
GALLE DATASET
======================================================================
Shape: (1525632, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Galle,1,5.84691,80.221,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,16.4,61,ENE,22.3,0.0,0.0,48,0.0,0.0,NaN
1,Galle,1,5.84691,80.221,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,16.6,56,NE,23.0,0.0,0.0,29,0.0,0.0,NaN
2,Galle,1,5.84691,80.221,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,16.8,55,NE,22.7,0.0,0.0,18,0.0,0.0,NaN
3,Galle,1,5.84691,80.221,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,17.1,60,ENE,23.8,0.0,0.0,22,0.0,0.0,NaN
4,Galle,1,5.84691,80.221,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,17.7,63,ENE,23.8,0.0,0.0,45,0.0,0.0,NaN

======================================================================
KANDY DATASET
======================================================================
Shape: (1736064, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Kandy,1,7.13069,80.53697,808.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,1.8,191,S,3.6,0.0,0.0,20,0.0,0.0,NaN
1,Kandy,1,7.13069,80.53697,808.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,3.3,193,SSW,7.2,0.0,0.0,36,0.0,0.0,NaN
2,Kandy,1,7.13069,80.53697,808.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,2.9,173,S,7.2,0.0,0.0,63,0.0,0.0,NaN
3,Kandy,1,7.13069,80.53697,808.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,1.9,158,SSE,5.8,0.0,0.0,91,0.0,0.0,NaN
4,Kandy,1,7.13069,80.53697,808.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,1.6,153,SSE,5.4,0.0,0.0,96,0.0,0.0,NaN

======================================================================
JAFFNA DATASET
======================================================================
Shape: (894336, 27)

Columns:
['District', 'PointID', 'Latitude', 'Longitude', 'Elevation_m', 'DateTime', 'Date', 'Day', 'Month', 'Year', 'Time', 'Season', 'Temperature_C', 'FeelsLike_C', 'Humidity_pct', 'DewPoint_C', 'Pressure_hPa', 'WindSpeed_kmh', 'WindDirection_deg', 'WindDirection_compass', 'WindGust_kmh', 'Rainfall_mm', 'Rain_mm', 'CloudCover_pct', 'SolarRadiation_Wm2', 'SunshineDuration_s', 'Visibility_m']

Data types:
District                  object
PointID                    int64
Latitude                 float64
Longitude                float64
Elevation_m              float64
DateTime                  object
Date                      object
Day                        int64
Month                      int64
Year                       int64
Time                      object
Season                    object
Temperature_C            float64
FeelsLike_C              float64
Humidity_pct               int64
DewPoint_C               float64
Pressure_hPa             float64
WindSpeed_kmh            float64
WindDirection_deg          int64
WindDirection_compass     object
WindGust_kmh             float64
Rainfall_mm              float64
Rain_mm                  float64
CloudCover_pct             int64
SolarRadiation_Wm2       float64
SunshineDuration_s       float64
Visibility_m             float64
dtype: object

First 5 rows:

,District,PointID,Latitude,Longitude,Elevation_m,DateTime,Date,Day,Month,Year,...,WindSpeed_kmh,WindDirection_deg,WindDirection_compass,WindGust_kmh,Rainfall_mm,Rain_mm,CloudCover_pct,SolarRadiation_Wm2,SunshineDuration_s,Visibility_m
0,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T00:00,2020-01-01,1,1,2020,...,13.7,67,ENE,22.0,0.0,0.0,97,0.0,0.0,NaN
1,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T01:00,2020-01-01,1,1,2020,...,13.7,63,ENE,19.1,0.0,0.0,97,0.0,0.0,NaN
2,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T02:00,2020-01-01,1,1,2020,...,12.4,64,ENE,18.7,0.0,0.0,97,0.0,0.0,NaN
3,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T03:00,2020-01-01,1,1,2020,...,13.9,65,ENE,18.4,0.1,0.1,95,0.0,0.0,NaN
4,Jaffna,1,9.56386,79.92646,0.0,2020-01-01T04:00,2020-01-01,1,1,2020,...,12.4,60,ENE,20.2,0.1,0.1,90,0.0,0.0,NaN